# Generated by Django 5.2.1 on 2025-05-11 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
