# Generated by Django 5.2.1 on 2025-05-22 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_feedback_feedback_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
